name: "Stop Brazil instance"
on:
  workflow_dispatch:

jobs:
  stop-brazil-instance:
    name: "Stop Brazil instance (54.207.194.197)"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRAZIL_INSTANCE }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRAZIL_INSTANCE }}
      AWS_REGION: sa-east-1

    steps:
      - name: Stop Brazil instance
        run: |
          aws ec2 stop-instances --instance-ids i-0a6c828181e221c1e
